<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitbfa618adfb857c8af6f1e2272b8c8d85
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitbfa618adfb857c8af6f1e2272b8c8d85::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitbfa618adfb857c8af6f1e2272b8c8d85::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitbfa618adfb857c8af6f1e2272b8c8d85::$classMap;

        }, null, ClassLoader::class);
    }
}
